### ISSUE TITLE
Better support for running single test

### ISSUE THREAD

**Issue by jk-1** [lihaoyi/utest#104]
Manual says:
If you want to only run a particular test file:
sbt> test-only -- HelloTests.HelloTestsuite
Or even a particular test within a particular file
sbt> test-only -- HelloTests.HelloTestsuite.hello
sbt> test-only -- HelloTests.HelloTestsuite.hello.world
sbt> test-only -- HelloTests.HelloTestsuite.test2

Proposal
1) Add support for running test with spaces in the name
sbt> test-only -- HelloTests.HelloTestsuite."hello world"

2) Add support for running test case with a given string in the name
sbt> test-only -- HelloTests.HelloTestsuite -z "hello world"
==>> This should run test case(s) having "hello world" as a part of the name.
Like in the accepted  answer of this SO question:
http://stackoverflow.com/questions/11159953/scalatest-in-sbt-is-there-a-way-to-run-a-single-test-without-tags

**Comment by lihaoyi** [comment]
> Add support for running test with spaces in the name
> sbt> test-only -- HelloTests.HelloTestsuite."hello world"

This should work in master since https://github.com/lihaoyi/utest/commit/01262919241694d7af169acc7f2e9600e360c04f

> Add support for running test case with a given string in the name
> sbt> test-only -- HelloTests.HelloTestsuite -z "hello world"

I'm reluctant to include this by default. I think the "correct" thing to do is to run stuff by their full name. If we'd include this, it would have to be done in a reasonably elegant manner that's not just string munging. Feel free to open a separate issue for this request alone
