### ISSUE TITLE
Add should matchers

### ISSUE THREAD

**Issue by antonkulaga** [lihaoyi/utest#14]
In most of the cases should matchers are more convenient than asserts.
It would be great to have some should matchers like in all normal (scalatest,scalaspecs2 and so on) testing frameworks

``` scala
foo.bar should beTrue
foo.bar shouldEqual foo2.bar
```

**Comment by SemanticBeeng** [comment]
I agree with keeping things "µ" and not have superfluous ways to checking things.

But would really love to have more syntactical common ground with Specs2 because many times one still needs to write Specs2 tests and not being able to use the same syntax for identical semantics is a .. missed opportunity. :-) 

Specs2 also has this great flexibility for scoping and "around" logic that would also make sense in uTest: http://etorreborre.github.io/specs2/guide/org.specs2.guide.Structure.html

Seems to me the spirit of uTest would be preserved if the two frameworks shared the "µ" parts, so to speak.

Wondering what @etorreborre would have to say about this.

Also, how would https://github.com/backuity/matchete be used from ScalaJS?

**Comment by etorreborre** [comment]
If you start adding context management, you are slowly leaving the "µ" world. In terms of assertions expressivity maybe you can try to use matchete or specs2-matchers (with `ShouldThrownMatchers`) with uTest simply because they will throw failure exceptions if they fail. 

I totally understand why @lihaoyi would want to keep uTest to the bare minimum and I think that this totally satisfies some users like Paul Phillips (well as much as something is able to satisfy P.P.)

**Comment by lihaoyi** [comment]
> So do I. I think this feature is important enough to be included into lib

```scala
Predef.assert(someCondition, "brief info about it")
```

Still works. uTest itself doesn't care, which is nice ^_^

> I totally understand why @lihaoyi would want to keep uTest to the bare minimum and I think that this totally satisfies some users like Paul Phillips (well as much as something is able to satisfy P.P.)

I think even as it is, @paulp isn't satisfied with uTest and is manually writing all his tests inside a `main` method.

**Comment by paulp** [comment]
True, I tried using utest and then I tore it out.

**Comment by SemanticBeeng** [comment]
Yes, there are ways around matchers but do we want uTest to have "acceptance tests"? (G/W/T, fixtures, scopes. contexts)

**Comment by SemanticBeeng** [comment]
Acceptance tests are closer to functionality and integration vs unit tests which are focused on a design unit at a time.

Specs2 has a few features that make it much more than a unit "test" framework but a "specification" framework.

G/W/T is probably the most expressive in this sense: http://etorreborre.github.io/specs2/guide/org.specs2.guide.structure.GivenWhenThenPage.html but there is extensive support for scoping, fixtures and other things useful for "functional tests".

This is some more http://stackoverflow.com/questions/4139095/unit-tests-vs-acceptance-tests

As a concrete example, I am testing the boundaries of uTest for writing more complex async tests and am unsure what is supposed to work and what not by by comparison to Specs2 (focus is on functionality and integration and not matchers).

See concrete some questions 

https://groups.google.com/d/msg/scala-js/53FhRvcduwc/yjybMUh1pNMJ
https://groups.google.com/d/msg/scala-js/53FhRvcduwc/knmhXZfCP9gJ
https://groups.google.com/d/msg/scala-js/53FhRvcduwc/33rj_a5xsDcJ

I believe the greatest thing about ScalaJS is not that one can write UI stuff in Scala but that you can write DRY business logic! For any complex business application, repeating the logic in JavaScript is simply not an option. 

As such we need uTest to support functional and integration testing!
q.e.d. :-)

Evidently I am still discovering this but if we could reuse appropriate design from Specs2 in uTest it would be beneficial.

**Comment by sLite** [comment]
@SemanticBeeng 
> Also, how would https://github.com/backuity/matchete be used from ScalaJS?

I wanted having the possibilty to use matchers too. In fact it's dead simple.

    import utest._
    import org.backuity.matchete.AssertionMatchers

    object WorldTest extends TestSuite with AssertionMatchers {
        val tests = TestSuite {
            "World has to say Hello! with Matchers"-{
                World.hello must beEqualTo("Hello!")
            }
        }
    }

**Comment by backuitist** [comment]
Splitting matchete into multiple modules might help you with your integration: https://github.com/backuity/matchete/issues/2
If people need that soon I could do it fairly quickly I believe.
